// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYNTMiBbD0tBSKJ1r1wALmzJtN2IDmkc',
    appId: '1:461366833824:web:1ea1e637f99fb1cd080fc5',
    messagingSenderId: '461366833824',
    projectId: 'image-labeling-app-4a469',
    authDomain: 'image-labeling-app-4a469.firebaseapp.com',
    storageBucket: 'image-labeling-app-4a469.firebasestorage.app',
    measurementId: 'G-511C6HWWD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCpsqXc4TEKJpGUW_LE3rQyXqu5NF3SE',
    appId: '1:461366833824:android:e6caa0282a378221080fc5',
    messagingSenderId: '461366833824',
    projectId: 'image-labeling-app-4a469',
    storageBucket: 'image-labeling-app-4a469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DXdclbCrdvxhyt6-M6RelsOcoOOvkrw',
    appId: '1:461366833824:ios:dca66227b7f51a25080fc5',
    messagingSenderId: '461366833824',
    projectId: 'image-labeling-app-4a469',
    storageBucket: 'image-labeling-app-4a469.firebasestorage.app',
    iosBundleId: 'com.example.imageLabelingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1DXdclbCrdvxhyt6-M6RelsOcoOOvkrw',
    appId: '1:461366833824:ios:dca66227b7f51a25080fc5',
    messagingSenderId: '461366833824',
    projectId: 'image-labeling-app-4a469',
    storageBucket: 'image-labeling-app-4a469.firebasestorage.app',
    iosBundleId: 'com.example.imageLabelingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYNTMiBbD0tBSKJ1r1wALmzJtN2IDmkc',
    appId: '1:461366833824:web:b1f59950f0801328080fc5',
    messagingSenderId: '461366833824',
    projectId: 'image-labeling-app-4a469',
    authDomain: 'image-labeling-app-4a469.firebaseapp.com',
    storageBucket: 'image-labeling-app-4a469.firebasestorage.app',
    measurementId: 'G-XQQ8JSJ4NL',
  );
}
